## Homework

### Part 1

In [1]:
revenues = [120, 250, 80, 310, 95]
tax_rate = 0.18
discount_rate = 0.10

In [3]:
r = revenues
r

[120, 250, 80, 310, 95]

In [6]:
[r * (1 + tax_rate) for r in revenues]

[141.6, 295.0, 94.39999999999999, 365.79999999999995, 112.1]

In [9]:
final = [r * (1 + tax_rate) * (1 - discount_rate) for r in revenues]
final

[127.44, 265.5, 84.96, 329.21999999999997, 100.89]

In [18]:
for r in revenues:
    if r > 100:
        print("True")
    else:
        print("False")

True
True
False
True
False

In [19]:
[r > 100 for r in revenues]

[True, True, False, True, False]

In [20]:
[300 > r > 100 for r in revenues]

[True, True, False, False, False]

If we don't put the parentheses, the calculation result will be incorrect.

### Part 2

In [21]:
sales = [120, 250, 80, 310, 95]

In [25]:
sales = [120, 250, 80, 310, 95]
total = 0

for value in sales:
    total = total + value

total

855

In [27]:
average = total / len(sales)
average

171.0

In [28]:
sales[3]

310

In [38]:
for s in sales:
    if s > 150:
        print(s)

250
310

In [42]:
new_sales = []

for s in sales:
    new_sales.append(s * 1.05)
print(new_sales)

[126.0, 262.5, 84.0, 325.5, 99.75]

### Part 3

In [ ]:
“Premium” if revenue > 250
“Standard” if 100 < revenue ≤ 250
“Low” otherwise

In [68]:
sales = [20, 80, 100, 130, 200, 250, 300, 350]
segments = []

for revenue in sales:

    if revenue > 250:
        segments.append("Premium")
    elif 100 < revenue <= 250:
        segments.append("Standard")
    else:
        segments.append("Low")

segments

['Low', 'Low', 'Low', 'Standard', 'Standard', 'Standard', 'Premium', 'Premium']

In [83]:
premium = segments.count("Premium")
standard = segments.count("Standard")
low = segments.count("Low")

print(f"Premium: {premium} \nStandard: {standard} \nLow: {low}")

Premium: 2
Standard: 3
Low: 3

### Part 4

In [24]:
customer_ids = [1, 2, 3, 3, 4, 5, 5, 6]

In [25]:
customer_set = set(customer_ids)    
customer_set

{1, 2, 3, 4, 5, 6}

In [26]:
customer_ids

[1, 2, 3, 3, 4, 5, 5, 6]

In [27]:
len(customer_ids)

8

In [28]:
len(customer_set)

6

### Part 5

In [84]:
customer = {
    "name": "Anna",
    "revenue": 250,
    "city": "Yerevan"
}

In [88]:
if customer["revenue"] > 200:
    customer["segment"] = "High"
else: 
    customer["segment"] = "Low"

customer

{'name': 'Anna', 'revenue': 250, 'city': 'Yerevan', 'segment': 'High'}

In [89]:
customer["revenue"] = 300
customer

{'name': 'Anna', 'revenue': 300, 'city': 'Yerevan', 'segment': 'High'}

In [91]:
del customer['city']
customer

{'name': 'Anna', 'revenue': 300, 'segment': 'High'}

In [3]:
customer = {
    "name": "Anna",
    "revenue": 250,
    "city": "Yerevan"
}
for key, value in customer.items():
    print(key,':', value)

name : Anna
revenue : 250
city : Yerevan

### Part 6

In [4]:
revenues = [120, 250, 80, 310, 95]

In [5]:
revenues_aftr_tax = [r * 0.9 for r in revenues]
revenues_aftr_tax

[108.0, 225.0, 72.0, 279.0, 85.5]

In [19]:
[r for r in revenues if r > 100]

[120, 250, 310]

In [25]:
revenues = [120, 250, 80, 310, 95]
labels = ["High" if r > 200 else "Normal" for r in revenues]
labels

['Normal', 'High', 'Normal', 'High', 'Normal']

### Part 7

In [30]:
revenues = [120, 250, 80, 310, 95]
import pandas as pd

data = {
    "revenue": revenues
}

df = pd.DataFrame(data)
df

   revenue
0      120
1      250
2       80
3      310
4       95

In [36]:
df["revenue_after_tax"] = df["revenue"] * 0.9
df

   revenue  revenue_after_tax
0      120              108.0
1      250              225.0
2       80               72.0
3      310              279.0
4       95               85.5

In [38]:
df.loc[df["revenue"] > 200, "Segment"] = "High"
df.loc[df["revenue"] <= 200, "Segment"] = "Normal"
df

   revenue  revenue_after_tax Segment
0      120              108.0  Normal
1      250              225.0    High
2       80               72.0  Normal
3      310              279.0    High
4       95               85.5  Normal

In [40]:
filter_df = df[df["revenue"] > 100]
filter_df

   revenue  revenue_after_tax Segment
0      120              108.0  Normal
1      250              225.0    High
3      310              279.0    High

In [46]:
df = df.drop("revenue_after_tax", axis=1)
df

   revenue Segment
0      120  Normal
1      250    High
2       80  Normal
3      310    High
4       95  Normal

In [47]:
print(df.shape)

(5, 2)