In [3]:
## Unzipping File
import zipfile
with zipfile.ZipFile("../data/raw/Archive.zip", "r") as zip_ref:
    zip_ref.extractall("../data/raw")

In [4]:
del zip_ref

In [5]:
## Import packages
import pandas as pd

In [6]:
pd.Series([10, 30, 30])

0    10
1    30
2    30
dtype: int64

In [7]:
df_orders = pd.read_csv("../data/raw/orders.csv")
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [8]:
print(type(df_orders))
print(f"The # of rows {df_orders.shape[0]} \n and the # of columns {df_orders.shape[1]}")
df_orders.shape

<class 'pandas.DataFrame'>
The # of rows 3421083
 and the # of columns 7

(3421083, 7)

In [9]:
## List of colums
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

In [10]:
shape = df_orders.shape

In [11]:
# del df_orders
shape

(3421083, 7)

In [12]:
df_orders1 = df_orders

In [13]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 182.7 MB

In [14]:
df_orders.dtypes

order_id                    int64
user_id                     int64
eval_set                      str
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

In [15]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [16]:
df_orders_new = df_orders.assign(
    is_weekend = df_orders["order_dow"].isin([0, 6]),
    is_morning = df_orders["order_hour_of_day"] < 12
)

In [17]:
df_orders_new.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,is_weekend,is_morning
0,2539329,1,prior,1,2,8,NaN,False,True
1,2398795,1,prior,2,3,7,15.0,False,True
2,473747,1,prior,3,3,12,21.0,False,False
3,2254736,1,prior,4,4,7,29.0,False,True
4,431534,1,prior,5,4,15,28.0,False,False

In [18]:
del df_orders

In [19]:
df_products = pd.read_csv('../data/raw/products.csv')
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [20]:
df_orders_new = df_orders.assign(
    is_weekend = df_orders["order_dow"].isin([0, 6]),
    is_morning = df_orders["order_hour_of_day"] < 12
)

NameError: name 'df_orders' is not defined

In [ ]:
df_orders["is_weekend"] = df_orders["order_dow"].isin([0, 6])
df_orders["is_morning"] = df_orders["order_hour_of_day"] < 12

df_orders.head()

In [ ]:
df_orders["days_since_prior_order"] = df_orders["days_since_prior_order"].fillna(0)

df_orders.head()

In [ ]:
df_orders_new = pd.read.csv('../data/processed/order.csv')

In [ ]:
df_departments = pd.read_csv("../data/raw/departments.csv")
df_departments.head()

In [ ]:
df_temp_t = df_departments.T
df_temp_t.head()

In [ ]:
import zipfile
with zipfile.ZipFile("../data/raw/Archive.zip", "r") as zip_ref:
    zip_ref.extractall("../data/raw")

## Importing data

In [29]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [23]:
df_orders = pd.read_csv('../data/raw/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [24]:
# Reading data
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [25]:
df_products = pd.read_csv("../data/raw/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [26]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['department_id', 'department'], dtype='str')
(21, 2)

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [27]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
print(df_aisles.columns)
print(df_aisles.shape)
df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='str')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [28]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

## Working with 'Orders'

In [30]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [ ]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 182.7 MB

In [ ]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [ ]:
df_orders.shape

(3421083, 7)

In [31]:
df_orders['order_id'].nunique()

3421083

In [32]:
if df_orders['order_id'].nunique() == df_orders.shape[0]:
    print('Happy')
else:
    print('Sad')

Happy

In [33]:
df_orders["eval_set"].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [34]:
df_orders['order_dow'].value_counts()

order_dow
0    600905
1    587478
2    467260
5    453368
6    448761
3    436972
4    426339
Name: count, dtype: int64

In [35]:
df_dow = df_orders['order_dow'].value_counts(ascending=True).reset_index()
df_dow

   order_dow   count
0          4  426339
1          3  436972
2          6  448761
3          5  453368
4          2  467260
5          1  587478
6          0  600905

In [36]:
df_dow.sort_values(['order_dow'])

   order_dow   count
6          0  600905
5          1  587478
4          2  467260
1          3  436972
0          4  426339
3          5  453368
2          6  448761

In [37]:
df_dow.to_csv('../data/processed/df_dow.csv', index=False)

In [38]:
df_ohod = df_orders['order_hour_of_day'].value_counts().reset_index().sort_values(['order_hour_of_day'])
df_ohod.head()

    order_hour_of_day  count
18                  0  22758
19                  1  12398
21                  2   7539
23                  3   5474
22                  4   5527

In [39]:
df_ohod.to_csv('../data/processed/ohod.csv', index=False)

In [40]:
df_orders["days_since_prior_order"].isna().sum()

np.int64(206209)

In [41]:
df_orders.loc[df_orders["order_number"] == 1, "days_since_prior_order"].isna().all()

np.True_

In [42]:
needed_columns = ['order_number','days_since_prior_order', 'user_id']

In [43]:
df_orders[['order_number','days_since_prior_order']].head()

   order_number  days_since_prior_order
0             1                     NaN
1             2                   15.00
2             3                   21.00
3             4                   29.00
4             5                   28.00

In [44]:
df_first_orders = df_orders[needed_columns][df_orders['order_number']  == 1].reset_index()
df_first_orders.drop(columns=['index'], inplace=True)
df_first_orders.head()

   order_number  days_since_prior_order  user_id
0             1                     NaN        1
1             1                     NaN        2
2             1                     NaN        3
3             1                     NaN        4
4             1                     NaN        5

In [45]:
df_orders.iloc[26]

order_id                  1374495
user_id                         3
eval_set                    prior
order_number                    1
order_dow                       1
order_hour_of_day              14
days_since_prior_order        NaN
Name: 26, dtype: object

In [46]:
df_orders["order_dow"].between(0, 6).all()

np.True_

In [47]:
df_orders["order_hour_of_day"].between(0, 23).all()

np.True_

In [48]:
df_orders_train = df_orders[df_orders["eval_set"] == "train"]
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [49]:
df_orders_train.drop(columns=["eval_set"])
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [50]:
del df_orders

In [51]:
df_orders_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [52]:
df_orders_products_train["reordered"].value_counts(dropna=False)

reordered
1    828824
0    555793
Name: count, dtype: int64

In [53]:
df_orders_products_train["reordered"].value_counts(normalize=True)

reordered
1   0.60
0   0.40
Name: proportion, dtype: float64

In [54]:
df_orders_products_train["add_to_cart_order"].describe()

count   1,384,617.00
mean            8.76
std             7.42
min             1.00
25%             3.00
50%             7.00
75%            12.00
max            80.00
Name: add_to_cart_order, dtype: float64

In [55]:
df_orders_first_atc = df_orders_products_train[df_orders_products_train["add_to_cart_order"]==1]

In [56]:
df_orders_first_atc['product_id'].value_counts()

product_id
24852    4605
13176    3889
27845    1144
47766     995
21137     900
         ...
7044        1
28344       1
40866       1
13539       1
40800       1
Name: count, Length: 17908, dtype: int64

In [85]:
df_proucts_aislesd = pd.merge (df_products, df_aisles, on="aisle_id", how="left")

In [87]:
df_proucts_aislesd.head()

,product_id,product_name,aisle_id,department_id,prices,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.80,cookies cakes
1,2,All-Seasons Salt,104,13,9.30,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.30,marinades meat preparation

In [89]:
df_products_aisles_department = pd.merge(df_proucts_aislesd, df_departments, on="department_id", how="left")
df_products_aisles_department.head()

,product_id,product_name,aisle_id,department_id,prices,aisle,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,cookies cakes,snacks
1,2,All-Seasons Salt,104,13,9.30,spices seasonings,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,tea,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen meals,frozen
4,5,Green Chile Anytime Sauce,5,13,4.30,marinades meat preparation,pantry

In [90]:
df_products_aisles_department.drop(columns=['aisle_id', 'department_id'], inplace=True)
df_products_aisles_department.head()

,product_id,product_name,prices,aisle,department
0,1,Chocolate Sandwich Cookies,5.80,cookies cakes,snacks
1,2,All-Seasons Salt,9.30,spices seasonings,pantry
2,3,Robust Golden Unsweetened Oolong Tea,4.50,tea,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,10.50,frozen meals,frozen
4,5,Green Chile Anytime Sauce,4.30,marinades meat preparation,pantry

In [91]:
df_products_aisles_department.head()

,product_id,product_name,prices,aisle,department
0,1,Chocolate Sandwich Cookies,5.80,cookies cakes,snacks
1,2,All-Seasons Salt,9.30,spices seasonings,pantry
2,3,Robust Golden Unsweetened Oolong Tea,4.50,tea,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,10.50,frozen meals,frozen
4,5,Green Chile Anytime Sauce,4.30,marinades meat preparation,pantry

In [ ]:
df_products_aisles_department.drop(columns=['_merge'], inplace=True)
df_products_aisles_department.head()

KeyError: "['_merge'] not found in axis"

In [93]:
del df_departments
del df_aisles
del df_products

In [94]:
df_products_aisles_department['department'].value_counts()

department
personal care      6565
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3449
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1116
babies             1081
alcohol            1056
pets                972
meat seafood        907
other               548
bulk                 38
Name: count, dtype: int64

In [95]:
df_products_aisles_department[df_products_aisles_department["_merge"] == "left_only"
].head()

KeyError: '_merge'

In [96]:
pd.crosstab(
    df_products_aisles_department["department"],
    df_products_aisles_department["aisle"]
)

aisle,air fresheners candles,asian foods,baby accessories,baby bath body care,baby food formula,bakery desserts,baking ingredients,baking supplies decor,beauty,beers coolers,...,spreads,tea,tofu meat alternatives,tortillas flat bread,trail mix snack mix,trash bags liners,vitamins supplements,water seltzer sparkling water,white wines,yogurt
department,,,,,,,,,,,,,,,,,,,,,
alcohol,0,0,0,0,0,0,0,0,0,387,...,0,0,0,0,0,0,0,0,147,0
babies,0,0,44,132,718,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bakery,0,0,0,0,0,297,0,0,0,0,...,0,0,0,241,0,0,0,0,0,0
beverages,0,0,0,0,0,0,0,0,0,0,...,0,894,0,0,0,0,0,344,0,0
breakfast,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bulk,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
canned goods,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dairy eggs,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1026
deli,0,0,0,0,0,0,0,0,0,0,...,0,0,159,0,0,0,0,0,0,0
dry goods pasta,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
frozen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
household,355,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,112,0,0,0,0
international,0,605,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
meat seafood,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
missing,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
other,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pantry,0,0,0,0,0,0,623,290,0,0,...,493,0,0,0,0,0,0,0,0,0
personal care,0,0,0,0,0,0,0,0,178,0,...,0,0,0,0,0,0,1038,0,0,0
pets,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
produce,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
snacks,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,69,0,0,0,0,0

In [97]:
df_train_transactions= pd.merge(df_orders_products_train, df_orders_train, on="order_id", how="left") 
df_train_transactions.head()

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,1,49302,1,1,112108,train,4,4,10,9.00
1,1,11109,2,1,112108,train,4,4,10,9.00
2,1,10246,3,0,112108,train,4,4,10,9.00
3,1,49683,4,0,112108,train,4,4,10,9.00
4,1,43633,5,1,112108,train,4,4,10,9.00

In [98]:
df_train_transactions.groupby("order_id").size().head()

order_id
1      8
36     8
38     9
96     7
98    49
dtype: int64

In [99]:
basket_size_by_order = (
    df_train_transactions
    .groupby(["order_id", "order_dow"])
    .size()
    .reset_index(name="basket_size")
)

basket_size_by_order.groupby("order_dow")["basket_size"].mean()

order_dow
0   11.80
1   10.47
2    9.96
3    9.84
4    9.74
5   10.16
6   10.97
Name: basket_size, dtype: float64

In [100]:
df_train_analytic = pd.merge(
    df_train_transactions,
    df_products_aisles_department,
    on="product_id",
    how="left",
    indicator=True
)

df_train_analytic.head()

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_name,prices,aisle,department,_merge
0,1,49302,1,1,112108,train,4,4,10,9.00,Bulgarian Yogurt,9.10,yogurt,dairy eggs,both
1,1,11109,2,1,112108,train,4,4,10,9.00,Organic 4% Milk Fat Whole Milk Cottage Cheese,2.00,other creams cheeses,dairy eggs,both
2,1,10246,3,0,112108,train,4,4,10,9.00,Organic Celery Hearts,4.50,fresh vegetables,produce,both
3,1,49683,4,0,112108,train,4,4,10,9.00,Cucumber Kirby,13.20,fresh vegetables,produce,both
4,1,43633,5,1,112108,train,4,4,10,9.00,Lightly Smoked Sardines in Olive Oil,1.70,canned meat seafood,canned goods,both

In [101]:
df_train_analytic["department"].value_counts()

department
produce            409087
dairy eggs         217051
snacks             118862
beverages          113962
frozen             100426
pantry              81242
bakery              48394
canned goods        46799
deli                44291
dry goods pasta     38713
household           35986
meat seafood        30307
breakfast           29552
personal care       21599
babies              14941
international       11902
missing              8251
alcohol              5602
pets                 4497
other                1795
bulk                 1359
Name: count, dtype: int64

In [ ]:
pd.crosstab(
    df_train_analytic["department"],
    df_train_analytic["reordered"]
)

reordered             0       1
department
alcohol            2203    3399
babies             6857    8084
bakery            17702   30692
beverages         38960   75002
breakfast         12654   16898
bulk                573     786
canned goods      24017   22782
dairy eggs        70549  146502
deli              16924   27367
dry goods pasta   19828   18885
frozen            44258   56168
household         20614   15372
international      7380    4522
meat seafood      12400   17907
missing            5103    3148
other              1098     697
pantry            51744   29498
personal care     14309    7290
pets               1663    2834
produce          137201  271886
snacks            49760   69102

In [102]:
pd.crosstab(
    df_train_analytic["order_dow"],
    df_train_analytic["reordered"],
    normalize="index"
)

reordered    0    1
order_dow
0         0.39 0.61
1         0.40 0.60
2         0.41 0.59
3         0.41 0.59
4         0.41 0.59
5         0.39 0.61
6         0.41 0.59

In [103]:
del df_orders_products_train
del df_orders_train

In [104]:
df_customers = pd.read_csv('../data/raw/customers.csv')
df_customers.head()

,Unnamed: 0,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [75]:
df_states= pd.read_csv('../data/raw/states.csv')
df_states.head()

   Unnamed: 0          state     region     division
0           0    Connecticut  Northeast  New England
1           1          Maine  Northeast  New England
2           2  Massachusetts  Northeast  New England
3           3  New Hampshire  Northeast  New England
4           4   Rhode Island  Northeast  New England

In [105]:
df_customers = df_customers.rename(columns={"STATE": "state"})
df_customers.head()

,Unnamed: 0,user_id,First Name,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income
0,0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [106]:
df_customers_states = pd.merge(
    df_customers,
    df_states,
    on="state",
    how="left"
)

df_customers_states.head()

,Unnamed: 0_x,user_id,First Name,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,Unnamed: 0_y,region,division
0,0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665,17,Midwest,West North Central
1,1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285,43,West,Mountain
2,2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568,40,West,Mountain
3,3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049,14,Midwest,West North Central
4,4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374,25,South,South Atlantic

In [107]:
 df_train_analytic.head()

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_name,prices,aisle,department,_merge
0,1,49302,1,1,112108,train,4,4,10,9.00,Bulgarian Yogurt,9.10,yogurt,dairy eggs,both
1,1,11109,2,1,112108,train,4,4,10,9.00,Organic 4% Milk Fat Whole Milk Cottage Cheese,2.00,other creams cheeses,dairy eggs,both
2,1,10246,3,0,112108,train,4,4,10,9.00,Organic Celery Hearts,4.50,fresh vegetables,produce,both
3,1,49683,4,0,112108,train,4,4,10,9.00,Cucumber Kirby,13.20,fresh vegetables,produce,both
4,1,43633,5,1,112108,train,4,4,10,9.00,Lightly Smoked Sardines in Olive Oil,1.70,canned meat seafood,canned goods,both

In [108]:
 df_train_analytic.columns

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered', 'user_id',
       'eval_set', 'order_number', 'order_dow', 'order_hour_of_day',
       'days_since_prior_order', 'product_name', 'prices', 'aisle',
       'department', '_merge'],
      dtype='str')

In [109]:
df_customers_states.columns

Index(['Unnamed: 0_x', 'user_id', 'First Name', 'Surnam', 'Gender', 'state',
       'Age', 'date_joined', 'n_dependants', 'fam_status', 'income',
       'Unnamed: 0_y', 'region', 'division'],
      dtype='str')

In [110]:
df_train_analytic_final = pd.merge(
    df_train_analytic,
    df_customers_states,
    on="user_id",
    how="left"
)

df_train_analytic_final.head()

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,...,Gender,state,Age,date_joined,n_dependants,fam_status,income,Unnamed: 0_y,region,division
0,1,49302,1,1,112108,train,4,4,10,9.00,...,Female,Florida,33,5/19/2018,2,married,36846,23,South,South Atlantic
1,1,11109,2,1,112108,train,4,4,10,9.00,...,Female,Florida,33,5/19/2018,2,married,36846,23,South,South Atlantic
2,1,10246,3,0,112108,train,4,4,10,9.00,...,Female,Florida,33,5/19/2018,2,married,36846,23,South,South Atlantic
3,1,49683,4,0,112108,train,4,4,10,9.00,...,Female,Florida,33,5/19/2018,2,married,36846,23,South,South Atlantic
4,1,43633,5,1,112108,train,4,4,10,9.00,...,Female,Florida,33,5/19/2018,2,married,36846,23,South,South Atlantic

In [111]:
df_train_analytic_final.drop(columns=["Unnamed: 0","eval_set"], inplace=True )

KeyError: "['Unnamed: 0'] not found in axis"

In [112]:
df_train_analytic_final.shape

(1384706, 28)

In [84]:
df_train_analytic_final.to_csv('../data/processed/df_train_analytic_final.csv', index=False)

NameError: name 'df_train_analytic_final' is not defined