## Merge

In [1]:
import pandas as pd

In [24]:
df_orders = pd.read_csv('../data/raw/orders.csv')
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [25]:
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')
df_orders_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [4]:
df_products = pd.read_csv("../data/raw/products.csv")

In [5]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')

In [6]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')

In [48]:
df_customers = pd.read_csv('../data/raw/customers.csv')
df_customers.head()

,Unnamed: 0,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [49]:
df_states= pd.read_csv('../data/raw/states.csv')
df_states.head()

   Unnamed: 0          state     region     division
0           0    Connecticut  Northeast  New England
1           1          Maine  Northeast  New England
2           2  Massachusetts  Northeast  New England
3           3  New Hampshire  Northeast  New England
4           4   Rhode Island  Northeast  New England

In [11]:
df_products_departments = pd.merge(df_products, df_departments, on="department_id", how="left")

In [28]:
df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks
1,2,All-Seasons Salt,104,13,9.3,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry

In [29]:
df_products_departments.drop(columns=['department_id'], inplace=True)

In [30]:
df_products_enriched = pd.merge(df_products_departments, df_aisles, on="aisle_id", how="left")

In [31]:
df_products_enriched.head()

,product_id,product_name,aisle_id,prices,department,aisle
0,1,Chocolate Sandwich Cookies,61,5.8,snacks,cookies cakes
1,2,All-Seasons Salt,104,9.3,pantry,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,4.5,beverages,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,10.5,frozen,frozen meals
4,5,Green Chile Anytime Sauce,5,4.3,pantry,marinades meat preparation

In [32]:
df_products_enriched.drop(columns=['aisle_id'], inplace=True)

In [39]:
df_train_transactions = pd.merge(df_orders, df_orders_products_train, on="order_id", how="inner")

In [38]:
df_train_transactions.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,2539329,1,prior,1,2,8,NaN,NaN,NaN,NaN
1,2398795,1,prior,2,3,7,15.0,NaN,NaN,NaN
2,473747,1,prior,3,3,12,21.0,NaN,NaN,NaN
3,2254736,1,prior,4,4,7,29.0,NaN,NaN,NaN
4,431534,1,prior,5,4,15,28.0,NaN,NaN,NaN

In [43]:
df_train_analytic = pd.merge(df_train_transactions, df_products_enriched, on="product_id", how="left", indicator=True)

In [44]:
df_train_analytic.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,prices,department,aisle,_merge
0,1187899,1,train,11,4,8,14.0,196,1,1,Soda,9.0,beverages,soft drinks,both
1,1187899,1,train,11,4,8,14.0,25133,2,1,Organic String Cheese,8.6,dairy eggs,packaged cheese,both
2,1187899,1,train,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,12.6,dairy eggs,yogurt,both
3,1187899,1,train,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,1.0,household,paper goods,both
4,1187899,1,train,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,6.8,snacks,candy chocolate,both

In [45]:
df_train_analytic.drop(columns=['eval_set','product_id','_merge'], inplace=True)

In [46]:
df_train_analytic.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,product_name,prices,department,aisle
0,1187899,1,11,4,8,14.0,1,1,Soda,9.0,beverages,soft drinks
1,1187899,1,11,4,8,14.0,2,1,Organic String Cheese,8.6,dairy eggs,packaged cheese
2,1187899,1,11,4,8,14.0,3,1,0% Greek Strained Yogurt,12.6,dairy eggs,yogurt
3,1187899,1,11,4,8,14.0,4,1,XL Pick-A-Size Paper Towel Rolls,1.0,household,paper goods
4,1187899,1,11,4,8,14.0,5,1,Milk Chocolate Almonds,6.8,snacks,candy chocolate

In [47]:
df_train_analytic.shape

(1384706, 12)

In [51]:
df_customers = df_customers.rename(columns={'STATE': 'state'})

In [53]:
df_customers_states = pd.merge(df_customers, df_states, on="state", how="left")

In [54]:
df_customers_states.head()

,Unnamed: 0_x,user_id,First Name,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,Unnamed: 0_y,region,division
0,0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665,17,Midwest,West North Central
1,1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285,43,West,Mountain
2,2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568,40,West,Mountain
3,3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049,14,Midwest,West North Central
4,4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374,25,South,South Atlantic

In [55]:
df_train_analytic_final = pd.merge(df_train_analytic, df_customers_states, on="user_id", how="left")

In [56]:
df_train_analytic_final.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,product_name,prices,...,Gender,state,Age,date_joined,n_dependants,fam_status,income,Unnamed: 0_y,region,division
0,1187899,1,11,4,8,14.0,1,1,Soda,9.0,...,Female,Alabama,31,2/17/2019,3,married,40423,30,South,East South Central
1,1187899,1,11,4,8,14.0,2,1,Organic String Cheese,8.6,...,Female,Alabama,31,2/17/2019,3,married,40423,30,South,East South Central
2,1187899,1,11,4,8,14.0,3,1,0% Greek Strained Yogurt,12.6,...,Female,Alabama,31,2/17/2019,3,married,40423,30,South,East South Central
3,1187899,1,11,4,8,14.0,4,1,XL Pick-A-Size Paper Towel Rolls,1.0,...,Female,Alabama,31,2/17/2019,3,married,40423,30,South,East South Central
4,1187899,1,11,4,8,14.0,5,1,Milk Chocolate Almonds,6.8,...,Female,Alabama,31,2/17/2019,3,married,40423,30,South,East South Central

In [58]:
df_train_analytic_final.drop(columns=['Unnamed: 0_y','user_id'], inplace=True)

In [59]:
df_train_analytic_final.head()

,order_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,product_name,prices,department,...,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,1187899,11,4,8,14.0,1,1,Soda,9.0,beverages,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,1187899,11,4,8,14.0,2,1,Organic String Cheese,8.6,dairy eggs,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,1187899,11,4,8,14.0,3,1,0% Greek Strained Yogurt,12.6,dairy eggs,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,1187899,11,4,8,14.0,4,1,XL Pick-A-Size Paper Towel Rolls,1.0,household,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,1187899,11,4,8,14.0,5,1,Milk Chocolate Almonds,6.8,snacks,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central

In [60]:
df_train_analytic_final.shape

(1384706, 23)